component: scf
name: scfdemo

inputs:
  src: ./src
  runtime: Nodejs10.15
  region: ap-guangzhou
  handler: index.main_handler
  events:
    - apigw:
        parameters:
          protocols:
            - http
            - https
          environment: release
          endpoints:
            - path: /
              method: GET
